#!/bin/bash

echo "start codes check,please wait..."

DIR=$(cd $(dirname $0) && pwd )

# 执行detekt检查
OUTPUT=`cd $DIR/../../; ./gradlew -PcheckCommit="true" detekt`

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "$OUTPUT"
  exit -1
fi

# 执行java checkstyle检查
OUTPUT=`cd $DIR/../../; ./gradlew -PcheckCommit="true" checkstyle`

EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "$OUTPUT"
  exit $EXIT_CODE
fi
